# Generated by Django 4.2.10 on 2024-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_remove_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admins', models.ManyToManyField(to='meetup.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
