# Generated by Django 4.2.10 on 2024-02-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='groups', to='meetup.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='groups_with_admin', to='meetup.user'),
        ),
    ]
