# Generated by Django 4.2.10 on 2024-02-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_group_participants_alter_group_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.group')),
                ('rsvp', models.ManyToManyField(related_name='rsvp', to='meetup.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
