# Generated by Django 4.2.10 on 2024-02-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(default=[], related_name='groups', to='meetup.user'),
        ),
    ]
